### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by l0u1sg** [l0u1sg/mosaic-project-NSI#3]
- [x] Créer une fonction pour resize l'image dans un bon format dans
- [x] Changer `mean_folder()` ...
- [x] Changer `mean_value()` pour faire la moyenne d'un bloc de 20x20 dans une image
- [x] Faire fonction `create_mosaic()`:
Fonction qui prends les dimension de l'image originale et en crée une copie vierge & place les vignettes de 20x20 en fonction de leur moyenne de couleurs par rapport à l'image original
- [ ] Retester les fonctions et chercher de potentiel erreur et les fixer 
- [ ] Enlever fonctions inutiles
- [ ] Faire spécifications fonctions & description code + complétion du README
